### ISSUE TITLE
Issue on order flow

### ISSUE THREAD

**Issue by homemaderepo** [quadra-informatique/Magento-Paybox#7]
Hi,
we actualy have issues on order flow since we use paybox module. When a customer make an order, and pay, when he come back, the order get the "processing" state as configured and the invoice is automaticaly created.

The issue is that when we ship the order, it did not change the status to "complete", even if all items are shipped.

We also use paypal, checkmo as payment means and don't have this issue. All shipped orders are automaticaly changed to  "complete".

The only way we have to set it to complete is to make a new invoice, or shipped it again !

We are on a Magento 1.4.1.1. 

Many thanks for your answer.

Jerome

**Comment by mpasquin** [comment]
Hi,

Sorry for the late answer...
Our extension is no longer maintained.

Please, upgrade to the official one: http://www.magentocommerce.com/magento-connect/paybox-epayment-1.html

Regards,
Quadra Team
